version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: on-failure
    cpu_count: 1
    networks:
      infra_network:
    environment:
      - VIRTUAL_HOST=io-operations.xyz
      - VIRTUAL_PORT=9443
      - BASE_URL=/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/hserver/portainer/data:/data"
  vault:
    image: hashicorp/vault
    container_name: vault
    restart: on-failure
    cpu_count: 1
    networks:
      infra_network:
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - "/home/hserver/vault/logs:/vault/logs"
      - "/home/hserver/vault/file:/vault/file"
      - "/home/hserver/vault/config:/vault/config"
    command:
      - "server"
  mongodb:
    image: bitnami/mongodb:7.0.4
    container_name: mongodb
    restart: on-failure
    cpu_count: 4
    networks:
      infra_network:
    volumes:
      - "/home/hserver/mongodb/data:/bitnami/mongodb:rw"
    ports:
      - "27017:27017"
    env_file:
      - "/home/hserver/mongo.env"
  postgresql:
    image: postgres:16.1-alpine3.19
    container_name: postgresql
    restart: on-failure
    cpu_count: 1
    networks:
      infra_network:
    volumes:
      - "/home/hserver/postgresql/data:/var/lib/postgresql/data:Z"
    env_file:
      - "/home/hserver/postgres.env"
  teamcity:
    image: jetbrains/teamcity-server:2023.11.1-linux
    container_name: teamcity
    restart: on-failure
    cpu_count: 1
    networks:
      infra_network:
    volumes:
      - "/home/hserver/teamcity/data:/data/teamcity_server/datadir:Z"
      - "/home/hserver/teamcity/logs:/opt/teamcity/logs:Z"
      - "/home/hserver/teamcity/conf:/opt/teamcity/conf :Z"
    environment:
      - TEAMCITY_CONTEXT=/teamcity
    links:
      - postgresql
  teamcity-agent:
    image: jetbrains/teamcity-agent:2023.11.1
    container_name: teamcity-agent
    restart: on-failure
    user: root
    cpu_count: 1
    networks:
      infra_network:
    volumes:
      - "/home/hserver/teamcity_agent/config:/data/teamcity_agent/conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/hserver/teamcity_agent/work:/opt/buildagent/work"
      - "/home/hserver/teamcity_agent/temp:/opt/buildagent/temp"
      - "/home/hserver/teamcity_agent/tools:/opt/buildagent/tools"
      - "/home/hserver/teamcity_agent/plugins:/opt/buildagent/plugins"
      - "/home/hserver/teamcity_agent/system:/opt/buildagent/system"
    environment:
      - SERVER_URL=http://teamcity:8111/teamcity
    links:
      - teamcity
  nginx:
    image: nginx:stable-alpine3.17
    container_name: nginx
    restart: on-failure
    cpu_count: 1
    networks:
      infra_network:
    volumes:
      - "/home/hserver/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/home/hserver/certbot/www/:/var/www/certbot:ro"
      - "/home/hserver/certbot/conf:/etc/letsencrypt:rw"
    ports:
      - "80:80"
      - "443:443"
    links:
      - portainer
      - teamcity
#  certbot:
#    image: certbot/certbot:amd64-latest
#    restart: on-failure
#    volumes:
#      - "/home/hserver/certbot/www/:/var/www/certbot/:rw"
#      - "/home/hserver/certbot/conf/:/etc/letsencrypt/:rw"
#    links:
#      - nginx


networks:
  infra_network:
    name: infra_network

